language: java

sudo: false

jdk:
  - oraclejdk7

before_script:
  - "mvn clean install -Dmaven.test.skip=true"

script:
  - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent install"

after_success: |
  if [ $TRAVIS_PULL_REQUEST == false -a $TRAVIS_BRANCH == 'quality' ]; then
    wget https://raw.githubusercontent.com/cyChop/dev-resources/master/sonar/sonar.settings.xml
    mvn -Psonar sonar:sonar --settings sonar.settings.xml
  fi
