= Tree comparer
Cyrille Chopelet <cyrille.chopelet@mines-nancy.org>

// Set your repository informations here.
:github-user: cyChop
:github-repo: tree-comparer
:pom-groupid: org.keyboardplaying
:pom-artifactid: tree-comparer
:waffle: {github-repo}
:license-name: ASF 2.0
:license-shield: ASF_2.0
:license-url: http://www.apache.org/licenses/LICENSE-2.0


// The badges. Should not require any change.
:url-shields: http://img.shields.io/
:url-sonar: sonar.keyboardplaying.org
image:{url-shields}travis/{github-user}/{github-repo}/master.svg[Build status, link="https://travis-ci.org/{github-user}/{github-repo}"]
image:{url-shields}sonar/http/{url-sonar}/{pom-groupid}:{pom-artifactid}/coverage.svg[Test coverage, link="http://{url-sonar}/drilldown/measures/?id={pom-groupid}:{pom-artifactid}&metric=coverage"]
image:{url-shields}sonar/http/{url-sonar}/{pom-groupid}:{pom-artifactid}/tech_debt.svg[Technical debt, link="http://{url-sonar}/dashboard/index?id={pom-groupid}:{pom-artifactid}"]
image:https://badge.waffle.io/{github-user}/{waffle}.svg?label=ready&title=Ready[Waffle, link="https://waffle.io/{github-user}/{waffle}"]
image:{url-shields}badge/license-{license-shield}-blue.svg[License: {license-name}, link="{license-url}"]

// Now, the main documentation.

== What's this?

This project is an algorithm I designed to compare two or more trees.
The algorithm is designed so that it can be applied to any kind of tree (understand: a node with children nodes, with children nodes, ...).

The most immediate application is obviously the comparison of directories.
This is why the project already contains an implementation for files.
It was proofed by (accurately) comparing the configuration of several environments (local, development, quality & acceptance, production).

== What's in this?

- `tree-comparer-model`: the objects needed for the use of the algorithm.
- `tree-comparer-algorithm`: the comparison algorithm properly.
- `tree-comparer-reporter`: a tool to generate a report from a compared tree.
- `tree-comparer-file`: the implementation of the models and utilities for directory comparison.
- `plaintext-diff`: a plaintext comparison utility, extracted from the https://www.apache.org/licenses/LICENSE-2.0[ASF 2.0 licensed] https://code.google.com/p/google-diff-match-patch/[Diff Match Patch project]; used mainly for reporting.

== The concurrence

Some products already exist and are easier to use, with an interactive user interface.

- http://winmerge.org/[WinMerge] can compare two directories and enables interactive browsing of the differences.
- http://kdiff3.sourceforge.net/[KDiff3] can compare up to three directories.

This algorithm however can compare a virtually unlimited number of trees.
