= Tree comparer
Cyrille Chopelet <cyrille.chopelet@mines-nancy.org>

// Set your repository informations here.
:github-user: cyChop
:github-repo: tree-comparer
:pom-groupid: org.keyboardplaying
:pom-artifactid: tree-comparer
:license-name: ASF 2.0
:license-shield: ASF_2.0
:license-url: http://www.apache.org/licenses/LICENSE-2.0


// The badges. Should not require any change.
:url-shields: http://img.shields.io/
:url-sonar: sonar.keyboardplaying.org
image:{url-shields}travis/{github-user}/{github-repo}/master.svg[Build status, link="https://travis-ci.org/{github-user}/{github-repo}"]
image:{url-shields}sonar/http/{url-sonar}/{pom-groupid}:{pom-artifactid}/coverage.svg[Test coverage, link="http://{url-sonar}"]
image:{url-shields}sonar/http/{url-sonar}/{pom-groupid}:{pom-artifactid}/tech_debt.svg[Technical debt, link="http://{url-sonar}"]
image:{url-shields}badge/license-{license-shield}-blue.svg[License: {license-name}, link="{license-url}"]

// Now, the main documentation.

== Goal

This algorithm was designed to provide a way to easily compare several trees.

The provided implementation was more specifically designed to compare file trees, and was to be used to compare the configurations of several environments (such as development, test, production) for a professional project.

http://winmerge.org/[WinMerge] can compare two directories and http://kdiff3.sourceforge.net/[KDiff3] can do the same for up to three. This algorithm can do it for a virtually unlimited number (virtually only, because you still need the memory to store it).
